Remove annotations unsupported in kotlin-native
Caused these errors:

 Task :sample1-native:compileDebugKotlinNative
Undefined symbols for architecture x86_64:
  "_kfun:com.soywiz.korge.bitmapfont.FontDescriptor.<get-chars>()kotlin.String", referenced from:
      _kfun:com.soywiz.korge.bitmapfont.BitmapFontAsyncFactory.$create$1.doResume(kotlin.Any?;kotlin.Throwable?)kotlin.Any? in combined.o
  "_kfun:com.soywiz.korge.bitmapfont.FontDescriptor.<get-face>()kotlin.String", referenced from:
      _kfun:com.soywiz.korge.bitmapfont.BitmapFontAsyncFactory.$create$1.doResume(kotlin.Any?;kotlin.Throwable?)kotlin.Any? in combined.o
  "_kfun:com.soywiz.korge.bitmapfont.FontDescriptor.<get-size>()ValueType", referenced from:
      _kfun:com.soywiz.korge.bitmapfont.BitmapFontAsyncFactory.$create$1.doResume(kotlin.Any?;kotlin.Throwable?)kotlin.Any? in combined.o
  "_kfun:com.soywiz.korge.resources.Path.<get-path>()kotlin.String", referenced from:
      _kfun:com.soywiz.korge.atlas.Atlas.Factory.$create$1.doResume(kotlin.Any?;kotlin.Throwable?)kotlin.Any? in combined.o
      _kfun:com.soywiz.korge.resources.ResourcesRoot.get(com.soywiz.korge.resources.Path)com.soywiz.korio.file.VfsFile in combined.o
      _kfun:com.soywiz.korge.audio.SoundFile.Factory.$create$5.doResume(kotlin.Any?;kotlin.Throwable?)kotlin.Any? in combined.o
ld: symbol(s) not found for architecture x86_64
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld invocation reported errors